# Generated by Django 3.0.3 on 2020-02-11 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('produce_products', '0001_initial'), ('produce_products', '0002_auto_20200204_1220'), ('produce_products', '0003_auto_20200204_1225'), ('produce_products', '0004_auto_20200204_1229'), ('produce_products', '0005_product_product_image'), ('produce_products', '0006_auto_20200206_1210'), ('produce_products', '0007_auto_20200207_0848'), ('produce_products', '0008_auto_20200207_1137')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('product_description', models.TextField()),
                ('product_color', models.TextField()),
                ('price', models.IntegerField()),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_image', models.ImageField(default='image', upload_to='product_image')),
                ('created_on', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
