# Generated by Django 3.0.3 on 2020-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce_products', '0001_squashed_0008_auto_20200207_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
