# Generated by Django 3.0.3 on 2020-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce_products', '0003_auto_20200213_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
