# Generated by Django 3.0.3 on 2020-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce_products', '0004_auto_20200204_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='image', upload_to='product_image'),
        ),
    ]
