# Generated by Django 3.0.3 on 2020-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produce_products', '0005_auto_20200213_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ImageField(upload_to=''),
        ),
    ]
